config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "static_pages#landing"

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  resources :users, only: %i[new create]
  resources :name_tags, only: %i[index new create]
  resource :profile, only: %i[show edit update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/logo.rb
class Logo < ApplicationRecord
  mount_uploader :image_url, ImageUrlUploader

  has_many :name_tag_logos, dependent: :destroy
  has_many :name_tags, through: :name_tag_logos
end

app/models/name_tag.rb
class NameTag < ApplicationRecord
  belongs_to :user
  has_many :name_tag_logos, dependent: :destroy
  has_many :logos, through: :name_tag_logos

  validates :publicity, inclusion: { in: [true, false]}
  
end

app/models/name_tag_logo.rb
class NameTagLogo < ApplicationRecord
  belongs_to :name_tag
  belongs_to :logo
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  mount_uploader :avatar, AvatarUploader

  has_many :name_tags, dependent: :destroy

  validates :password, length: { minimum: 8 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true, presence: true
  validates :nickname, presence: true, length: { maximum: 20}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :info, :warning, :danger
  before_action :require_login

  private
  
  def not_authenticated
    redirect_to login_path, warning: t('defaults.message.require_login')
  end
end

app/controllers/name_tags_controller.rb
class NameTagsController < ApplicationController
  before_action :set_name_tag, only: %i[show edit update destroy]

  def index
    @name_tags = NameTag.all.includes(:user).order(created_at: :desc)
  end

  def show; end

  def new
    @name_tag = NameTag.new
    @logos = Logo.all
  end

  def edit; end

  def update; end

  def create
    @name_tag = current_user.name_tags.build(name_tags_params)
    if @name_tag.save
      redirect_to name_tags_path, success: t('defaults.message.created', item: NameTag.model_name.human)
    else
      flash.now[:danger] = t('defaults.message.not_created', item: NameTag.model_name.human)
      @logos = Logo.all
      render :new, status: :unprocessable_entity
    end
  end

  def destroy; end

  private

  def set_name_tag
    @name_tag = NameTag.find(params[:id])
  end

  def name_tags_params
    params.require(:name_tag).permit(:publicity, logo_ids: [])
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: %i[ edit update ]

  def edit; end

  def show; end

  def update
    if @user.update(user_params)
      redirect_to profile_path, success: t('defaults.message.updated', item: User.model_name.human)
    else
      flash.now[:danger] = t('defaults.message.not_updated', item: User.model_name.human)
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_profile
    @user = User.find(current_user.id)
  end

  def user_params
    params.require(:user).permit(:email, :nickname, :avatar, :avatar_cache)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :require_login, only: %i[landing]
  def landing
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]
  def new; end

  def create
    @user = login(params[:email], params[:password])
    if @user
      redirect_back_or_to root_path, success: t('.success')
    else
      flash.now[:danger] = t('.failure')
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    logout
    redirect_to root_path, status: :see_other, success: t('.success')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path, success: t('.success')
    else
      flash.now[:danger] = t('.failure')
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :nickname, :avatar, :avatar_cache)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_background_color(type)
    case type.to_sym
    when :notice then "bg-green-500"
    when :alert  then "bg-red-500"
    when :error  then "bg-yellow-500"
    else "bg-gray-500"
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-theme="synthwave">
  <head>
    <meta charset="utf-8">
    <%= favicon_link_tag('favicon.ico') %>
    <title>web_engineer_name_tag</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <% if logged_in? %>
      <%= render "shared/header" %>
    <% else %>
      <%= render "shared/before_login_header" %>
    <% end %>
    <%= render "shared/flash_message" %>
    <%= yield %> 
    <%= render "shared/footer" %>
  </body>
</html>

app/views/name_tags/_form.html.erb
<%= form_with model: name_tag, local: true do |f| %>
  <div class="bg-black shadow rounded-lg p-4">
    <h2 class="text-lg font-semibold"><%= current_user.nickname %></h2>
  </div>
  <div class="form-group">
    <%= f.label :publicity %>
    <%= f.check_box :publicity, class: 'form-control', rows: 10 %>
  </div>

  <div class="form-group">
    <%= f.label :logo %><br>
    <% @logos.each do |logo| %>
      <%= check_box_tag 'name_tag[logo_ids][]', logo.id, @name_tag.logos.include?(logo), id: "logo_#{logo.id}" %>
      <%= label_tag "logo_#{logo.id}", logo.name %>
      <% if logo.image_url.present? %>
        <%= image_tag logo.image_url.url, alt: logo.name, class: 'logo-image' %>
      <% end %>
      <br>
    <% end %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/name_tags/_name_tag.html.erb
<div class="bg-black shadow rounded-lg p-4">
  <h2 class="text-lg font-semibold"><%= name_tag.user.nickname %></h2>
  <% name_tag.logos.each do |logo| %>
    <div class="logo">
      <%= image_tag logo.image_url.url, alt: logo.name %>
    </div>
  <% end %>
</div>

app/views/name_tags/index.html.erb
<div class="container mx-auto py-4">
  <div class="grid grid-cols-2 gap-4">
    <% if @name_tags.present? %>
      <%= render @name_tags %>
    <% else %>
      <p><%= t('.no_results') %></p>
    <% end %>
  </div>
</div>

app/views/name_tags/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <h1><%= t('.title') %></h1>
      <%= render 'form', { name_tag: @name_tag } %>
    </div>
  </div>
</div>

app/views/profiles/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1">
      <h1><%= t('.title') %></h1>
      <%= form_with model: @user, url: profile_path, local: true do |f| %>

        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control mb-3' %>

        <%= f.label :nickname %>
        <%= f.text_field :nickname, class: 'form-control mb-3' %>

        <%= f.label :avatar %>
        <%= f.file_field :avatar, onchange: 'previewFileWithId(preview)', class: 'form-control mb-3', accept: 'image/*' %>
        <%= f.hidden_field :avatar_cache %>

        <div class='mt-3 mb-3'>
          <%= image_tag @user.avatar.url,
                        class: 'rounded-circle',
                        id: 'preview',
                        size: '100x100' %>
        </div>
        <%= f.submit class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/profiles/show.html.erb
<div class="container pt-3">
  <div class="row">
    <div class="col-md-10 offset-md-1">
      <h1 class="float-left mb-5">プロフィール</h1>
      <%= link_to '編集', edit_profile_path, class: 'btn btn-success float-right' %>
      <table class="table">
        <tr>
          <th scope="row">メールアドレス</th>
          <td><%= current_user.email %></td>
        </tr>
        <tr>
          <th scope="row">ニックネーム</th>
          <td><%= current_user.nickname %></td>
        </tr>
        <tr>
          <th scope="row">アバター</th>
          <td><%= image_tag current_user.avatar.url %></td>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/shared/_before_login_header.html.erb
<header>
  <div class="navbar bg-base-100">
    <div class="navbar-start">
      <div class="dropdown">
        <%= link_to root_path, class: 'btn' do %>
          <%= image_tag 'web_engineer_name_tag.png', alt: 'Web Engineer Name Tag' %>
        <% end %>
      </div>
    </div>
    <div class="navbar-end">
      <%= link_to t('defaults.sign_up'), new_user_path, class: 'btn' %>
      <%= link_to t('defaults.login'), login_path , class: "btn" %>
    </div>
  </div>
</header>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="<%= flash_background_color(message_type) %> px-4 py-2 rounded-md text-white mb-4">
    <%= message %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer p-10 bg-base-200 text-base-content">
  <nav>
    <h6 class="footer-title"><%= t('defaults.contact')%></h6> 
  </nav> 
  <nav>
    <h6 class="footer-title"><%= t('defaults.rules')%></h6> 
  </nav> 
  <nav>
    <h6 class="footer-title"><%= t('defaults.privacy')%></h6> 
  </nav>
</footer>

app/views/shared/_header.html.erb
<header>
  <div class="navbar bg-base-100">
    <div class="navbar-start">
      <div class="dropdown">
        <%= link_to root_path, class: 'btn' do %>
          <%= image_tag 'web_engineer_name_tag.png', alt: 'Web Engineer Name Tag' %>
        <% end %>
      </div>
    </div>
    <div class="navbar-end">
      <%= link_to t('profiles.show.title'), profile_path, class: 'btn' %>
      <%= link_to t('name_tags.new.title'), new_name_tag_path, class: 'btn' %>
      <%= link_to t('name_tags.index.title'), name_tags_path, class: "btn" %>
      <%= link_to t('defaults.logout'), logout_path, class: "btn", data: { turbo_method: :delete } %>
    </div>
  </div>
</header>

app/views/static_pages/landing.html.erb
<div class="hero min-h-screen" style="background-image: url(https://img.daisyui.com/images/stock/photo-1507358522600-9f71e620c44e.jpg);">
  <div class="hero-overlay bg-opacity-60"></div>
  <div class="hero-content text-center text-neutral-content">
    <div class="max-w-md">
      <h1 class="mb-5 text-5xl font-bold">Web_Engineer_Name_Tagへようこそ!</h1>
      <p class="mb-5">Webエンジニア向けのオリジナルな名札(ネームタグ)を作成し、自分をアピールしませんか?</p>
      <%= image_tag "name_tag_prototipe.png", alt: "Name Tag Prototipe" %>
      <p class="mb-5">※画像はイメージです。</p>
      <p class="mb-5">今回のバトランには間に合いませんでした🙇🏻‍♂️</p>
      <p>今後こうしたデザインにできるよう頑張ります。</p>
      <%= link_to t('defaults.sign_up'), new_user_path, class: 'btn' %>
    </div>
  </div>
</div>

app/views/user_sessions/new.html.erb
<!-- new.html.erb -->
<div class="container mx-auto flex justify-center items-center h-screen">
  <div class="w-full max-w-md">
    <h1 class="text-center text-2xl mb-6"><%= t '.title' %></h1>
    <%= form_with url: login_path, local: true, class: 'shadow-md rounded px-8 pt-6 pb-8 mb-4' do |f| %>
      <div class="form-group mb-4">
        <%= f.label :email, User.human_attribute_name(:email), class: 'block text-gray-700 text-sm font-bold mb-2' %>
        <%= f.email_field :email, class: 'form-control shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline' %>
      </div>
      <div class="form-group mb-4">
        <%= f.label :password, User.human_attribute_name(:password), class: 'block text-gray-700 text-sm font-bold mb-2' %>
        <%= f.password_field :password, class: 'form-control shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline' %>
      </div>
      <div class="flex items-center justify-center">
        <%= f.submit t('defaults.login'), class: 'btn btn-primary bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline w-full text-center', method: :delete %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<!--
<label class="input input-bordered flex items-center gap-2">
  Name
  <input type="text" class="grow" placeholder="Daisy" />
</label>
<label class="input input-bordered flex items-center gap-2">
  Email
  <input type="text" class="grow" placeholder="daisy@site.com" />
</label>
<label class="input input-bordered flex items-center gap-2">
  <input type="text" class="grow" placeholder="Search" />
  <kbd class="kbd kbd-sm">⌘</kbd>
  <kbd class="kbd kbd-sm">K</kbd>
</label>
<label class="input input-bordered flex items-center gap-2">
  <input type="text" class="grow" placeholder="Search" />
  <span class="badge badge-info">Optional</span>
</label>
-->

<div class="container mx-auto flex justify-center items-center h-screen">
  <div class="w-full max-w-md">
    <h1 class="text-center text-2xl mb-6"><%= t '.title' %></h1>
    <%= form_with model: @user, local: true, class: 'shadow-md rounded px-8 pt-6 pb-8 mb-4' do |f| %>
      <div class="form-group mb-4">
        <%= f.label :nickname, class: 'block text-gray-700 text-sm font-bold mb-2' %>
        <%= f.text_field :nickname, class: 'form-control shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline' %>
      </div>
      <div class="form-group mb-4">
        <%= f.label :email, class: 'block text-gray-700 text-sm font-bold mb-2' %>
        <%= f.email_field :email, class: 'form-control shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline' %>
      </div>
      <div class="form-group mb-4">
        <%= f.label :password, class: 'block text-gray-700 text-sm font-bold mb-2' %>
        <%= f.password_field :password, class: 'form-control shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline' %>
      </div>
      <div class="form-group mb-4">
        <%= f.label :password_confirmation, class: 'block text-gray-700 text-sm font-bold mb-2' %>
        <%= f.password_field :password_confirmation, class: 'form-control shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline' %>
      </div>
      <div class="flex items-center justify-between">
        <%= f.submit t('defaults.register'), class: 'btn btn-primary bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline text-center w-full' %>
      </div>
    <% end %>
  </div>
</div>